SET NEWP 0 SPA 1 PAGES 0 FEED OFF COLSEP ' | 'HEAD OFF TRIMS ON LINESIZE 1000;
select count(*) from files where nite='des20061005' and lower(imagetype)='src';
select count(*) from files where nite='des20061005' and lower(imagetype)='src';
select count(*) from files where nite='des20061005' and lower(imagetype)='src';
select count(*) from files where nite='des20061005' and lower(imagetype)='src';
select count(*) from files where nite='des20061005' and lower(imagetype)='src';
select count(*) from files where nite='des20061005' and lower(imagetype)='src';
select count(*) from files where nite='des20061005' and lower(imagetype)='src';
select count(*) from files where nite='des20061005' and lower(imagetype)='src';
select count(*) from files where nite='des20061005' and lower(imagetype)='zero' and ccd_number=9;
select count(*) from files where nite='des20061005' and lower(imagetype)='zero' and ccd_number=10;
select count(*) from files where nite='des20061005' and lower(imagetype)='zero' and ccd_number=11;
select count(*) from files where nite='des20061005' and lower(imagetype)='zero' and ccd_number=12;
select count(*) from files where nite='des20061005' and lower(imagetype)='zero' and ccd_number=13;
select count(*) from files where nite='des20061005' and lower(imagetype)='zero' and ccd_number=14;
select count(*) from files where nite='des20061005' and lower(imagetype)='zero' and ccd_number=15;
select count(*) from files where nite='des20061005' and lower(imagetype)='zero' and ccd_number=16;
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=9 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=10 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=11 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=12 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=13 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=14 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=15 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=16 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=9 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=10 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=11 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=12 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=13 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=14 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=15 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=16 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=9 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=10 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=11 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=12 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=13 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=14 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=15 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=16 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=9 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=10 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=11 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=12 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=13 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=14 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=15 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='dome flat' and ccd_number=16 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=9 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=10 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=11 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=12 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=13 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=14 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=15 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=16 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=9 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=10 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=11 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=12 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=13 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=14 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=15 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=16 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=9 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=10 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=11 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=12 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=13 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=14 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=15 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=16 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=9 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=10 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=11 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=12 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=13 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=14 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=15 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='object' and ccd_number=16 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=9 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=10 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=11 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=12 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=13 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=14 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=15 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=16 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=9 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=10 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=11 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=12 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=13 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=14 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=15 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=16 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=9 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=10 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=11 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=12 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=13 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=14 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=15 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=16 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=9 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=10 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=11 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=12 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=13 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=14 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=15 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='reduced' and ccd_number=16 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=9 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=10 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=11 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=12 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=13 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=14 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=15 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=16 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=9 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=10 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=11 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=12 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=13 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=14 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=15 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=16 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=9 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=10 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=11 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=12 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=13 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=14 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=15 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=16 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=9 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=10 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=11 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=12 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=13 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=14 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=15 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='remap' and ccd_number=16 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=9 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=10 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=11 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=12 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=13 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=14 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=15 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=16 and band='g';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=9 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=10 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=11 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=12 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=13 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=14 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=15 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=16 and band='r';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=9 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=10 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=11 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=12 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=13 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=14 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=15 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=16 and band='i';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=9 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=10 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=11 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=12 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=13 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=14 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=15 and band='z';
select count(*) from files where nite='des20061005' and lower(imagetype)='catalog' and ccd_number=16 and band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=9 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=10 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=11 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=12 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=13 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=14 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=15 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=16 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=9 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=10 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=11 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=12 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=13 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=14 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=15 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=16 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=9 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=10 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=11 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=12 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=13 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=14 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=15 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=16 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=9 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=10 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=11 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=12 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=13 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=14 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=15 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='reduced' and f.ccd_number=16 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=9 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=10 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=11 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=12 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=13 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=14 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=15 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=16 and f.band='g';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=9 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=10 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=11 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=12 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=13 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=14 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=15 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=16 and f.band='r';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=9 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=10 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=11 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=12 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=13 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=14 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=15 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=16 and f.band='i';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=9 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=10 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=11 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=12 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=13 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=14 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=15 and f.band='z';
select count(*) from objects o, files f where o.imageid=f.imageid and f.nite='des20061005' and lower(f.imagetype)='remap' and f.ccd_number=16 and f.band='z';
exit;
