SET TRIMOUT   ON
SET HEADING   OFF

select 'LOCATION_ID:' || LOCATION_ID,'LOCATION_NAME:' || LOCATION_NAME,'ARCHIVE_HOST:' || ARCHIVE_HOST,'ARCHIVE_ROOT:' || ARCHIVE_ROOT,'STAGING_HOST:' || STAGING_HOST,'STAGING_ROOT:' || STAGING_ROOT,'IP_SUBNET:' || IP_SUBNET, 'TRANSFER_HOST:' || TRANSFER_HOST, 'DOWNLOAD_DIR:' || DOWNLOAD_DIR, 'TRANSFER_ARGS_SMALL:' || TRANSFER_ARGS_SMALL, 'TRANSFER_ARGS_LARGE:' || TRANSFER_ARGS_LARGE from archive_sites;
quit;
