-- SET TRIMOUT   ON
-- SET HEADING   OFF

-- SET HEAD OFF TRIMS ON;

SET NEWP 0 SPA 1 ESC ON PAGES 0 FEED OFF COLSEP '|'HEAD OFF TRIMS ON LINESIZE 5000;

select 'LOCATION_ID:' || LOCATION_ID,'LOCATION_NAME:' || LOCATION_NAME,'ARCHIVE_HOST:' || ARCHIVE_HOST,'ARCHIVE_ROOT:' || ARCHIVE_ROOT,'STAGING_HOST:' || STAGING_HOST,'STAGING_ROOT:' || STAGING_ROOT,'IP_SUBNET:' || IP_SUBNET, 'TRANSFER_HOST:' || TRANSFER_HOST, 'DOWNLOAD_DIR:' || DOWNLOAD_DIR, 'TRANSFER_ARGS_SMALL:' || TRANSFER_ARGS_SMALL, 'TRANSFER_ARGS_LARGE:' || TRANSFER_ARGS_LARGE from archive_sites archive_sites;
quit;

