#!/usr/bin/env perl
########################################################################
#  $Id$
#
#  $Rev::                                  $:  # Revision of last commit.
#  $LastChangedBy::                        $:  # Author of last commit. 
#  $LastChangedDate::                      $:  # Date of last commit.
#
#  Authors: 
#         Michelle Gower (mgower@ncsa.uiuc.edu)
#         Darren Adams (dadams@ncsa.uiuc.edu)
#
#  Developed at: 
#  The National Center for Supercomputing Applications (NCSA).
#  with useful conversations with Jordi Cohen and Jim Phillips from the
#  Theoretical and Computation Biophysics Group at the University
#  of Illinois at Urbana-Champaign.
#
#  Copyright (C) 2007 Board of Trustees of the University of Illinois. 
#  All rights reserved.
#
#  DESCRIPTION:
#
#######################################################################

use strict;
use warnings;

use Getopt::Long;
use FindBin;
use lib "$FindBin::Bin/../lib";
use DES::utils::misc;
use DES::utils::hist;
use DES::desconfig;


my $version;
&Getopt::Long::Configure( 'noignorecase', 'no_autoabbrev');
Getopt::Long::GetOptions(
   'version|v' => \$version
);

my ($configfile);
my ($config);
my ($stage, $substagetype, $substage);
my $debugfh;
open $debugfh, "> despretask.out";
local *STDOUT = $debugfh;
local *STDERR = $debugfh;

if (scalar(@ARGV) >= 4)
{
  $configfile = $ARGV[0];
  $stage = $ARGV[1];
  $substagetype = $ARGV[2];
  $substage = $ARGV[3];
}
else
{
  print "Usage: despretask configfile stage substagetype substage\n";
  close $debugfh;
  exit $FAILURE;
}

# read sysinfo file
$config = new DES::desconfig;
$config->readConfig($configfile, 0, $debugfh);

logEvent($config, "$stage", "$substagetype", "$substage", "pretask");

close $debugfh;

exit 0;

